# Inspired by https://github.com/astral-sh/uv-docker-example/blob/main/Dockerfile
# Normally we would just deploy the wheel published during CI pipeline instead of moving all the repo

FROM {{ package_name }}_base:local

ARG PROJECT_NAME={{ package_name }}

# Log back to user for final configuration
USER appuser

# Folder to have repository mounted
COPY --chown=appuser:appuser . /home/appuser/${PROJECT_NAME}
WORKDIR /home/appuser/${PROJECT_NAME}

RUN uv sync --no-dev
ENV PATH="/home/appuser/${PROJECT_NAME}/.venv/bin:$PATH"

CMD ["{{ package_name }}"]